version: '3'

services:
  mirth_database:
    image: mysql:5.7
    volumes:
       - "./data/db:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=mirth-test"
      - "MYSQL_USER=mirth"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"
    networks:
      - mirth_connect
    deploy:
      mode: replicated
      replicas: 1


  mirth-connect::
    build: mirth-connect
    volumes:
      - "./data/spools/:/var/spool/mirth/:rw"
    ports:
      - "8080:8080"
      - "8443:8443"
    network:
      - mirth_connect
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8181:80"
    environment:
      - "MYSQL_USERNAME=root"
      - "MYSQL_PASSWORD=password"
    networks:
      - mirth_connect
    deploy:
      mode: replicated
      replicas: 1



networks:
  mirth_connect:
    driver: overlay

volumes:
  mirth_data: