version: '3'

services:
 
  mirth-connect:
    build: mirth-connect
    volumes:      
      - "./data/spools/:/var/spool/mirth/:rw"
    ports: 
      - "8080:8080"
      - "8443:8443"   
    depends_on:
      - mirth-database

 
