version: '3.3'

services:
  mirth-database:
    image: postgres:latest 
    volumes:
      - "./data/db:/var/lib/postgresql/data:rw"
    environment:
      - "POSTGRES_USER=mirth"
      - "POSTGRES_DATABASE=mirthdb"
      - "POSTGRES_PASSWORD=password"
    ports: 
      - "5432:5432"
    restart: always    

  mirth-connect:
    image: hedidin/hl7connect:dev2
    ports: 
      - "32768:32768"
      - "32772:32772"
      - "32811:32811"
      - "33650:33650"
      - "33551:33651"
      - "5001:5001"
      - "7010:7010"
      - "7011:7011"
      - "7012:7012"
      - "8008:8008"
      - "8009:8009"
      - "8042:8042"
      - "8080:8080"
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8181:8181"
      - "8182:8182"
      - "8443:8443"    
    depends_on:
      - mirth-database     
    
